import { useEffect, useState } from 'react';
import { CheckCircle2, Database, Mail, Save, ShieldCheck, Trash2 } from 'lucide-react';
import { fetchAdminSettings, fetchStorageSnapshot, runStorageCleanup, saveAdminSettings, sendTestEmail, type AdminSettings, type StorageSnapshot } from '@/lib/adminSettingsRepository';
const defaults: AdminSettings = { platform_name: 'LearnFlow', support_email: '', currency: 'USD', default_language: 'en', default_theme: 'system', enforce_mfa: false, jwt_expiration_minutes: 60, password_min_length: 8, password_require_uppercase: true, password_require_number: true, password_require_symbol: true, smtp_host: '', smtp_port: 587, smtp_username: '', smtp_password: '', smtp_from_email: '', smtp_use_tls: true };
const formatBytes = (value: number) => `${(value / (1024 * 1024)).toFixed(2)} MB`;
export function AdminSettingsEnhancements() {
  const [settings, setSettings] = useState<AdminSettings>(defaults); const [storage, setStorage] = useState<StorageSnapshot | null>(null); const [recipient, setRecipient] = useState(''); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const load = async () => { try { const [nextSettings, nextStorage] = await Promise.all([fetchAdminSettings(), fetchStorageSnapshot()]); setSettings({ ...defaults, ...nextSettings }); setStorage(nextStorage); } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : 'Unable to load new platform settings.'); } };
  useEffect(() => { void load(); }, []);
  const update = <K extends keyof AdminSettings>(key: K, value: AdminSettings[K]) => setSettings((current) => ({ ...current, [key]: value }));
  const save = async () => { setBusy(true); try { setSettings(await saveAdminSettings(settings)); setNotice('New platform settings saved.'); } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : 'New settings save failed.'); } finally { setBusy(false); } };
  const cleanup = async () => { setBusy(true); try { const result = await runStorageCleanup(); setStorage(result.storage); setNotice(`${result.deleted_files.length} temporary files cleaned.`); } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : 'Cleanup failed.'); } finally { setBusy(false); } };
  const testEmail = async () => { if (!recipient) { setError('Enter a recipient email.'); return; } setBusy(true); try { await sendTestEmail({ recipient, host: settings.smtp_host, port: settings.smtp_port, username: settings.smtp_username, password: settings.smtp_password, from_email: settings.smtp_from_email, use_tls: settings.smtp_use_tls }); setNotice('Test email sent.'); } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : 'SMTP test failed.'); } finally { setBusy(false); } };
  return <section className="card space-y-5 p-5"><div><p className="text-xs uppercase tracking-[0.12em] text-primary-600">New platform controls</p><h2 className="text-lg font-semibold">Configuration, security, storage, and email</h2></div>{error && <p className="text-sm text-red-600">{error}</p>}{notice && <p className="flex items-center gap-2 text-sm text-emerald-600"><CheckCircle2 className="h-4 w-4" />{notice}</p>}<div className="grid gap-4 md:grid-cols-2"><div><label className="label-text">Platform name</label><input value={settings.platform_name} onChange={(event) => update('platform_name', event.target.value)} className="input-field" /></div><div><label className="label-text">Currency</label><input value={settings.currency} onChange={(event) => update('currency', event.target.value)} className="input-field" /></div><div><label className="label-text">Language</label><input value={settings.default_language} onChange={(event) => update('default_language', event.target.value)} className="input-field" /></div><div><label className="label-text">JWT expiration minutes</label><input type="number" value={settings.jwt_expiration_minutes} onChange={(event) => update('jwt_expiration_minutes', Number(event.target.value))} className="input-field" /></div></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={settings.enforce_mfa} onChange={(event) => update('enforce_mfa', event.target.checked)} className="h-4 w-4 accent-primary-600" /><ShieldCheck className="h-4 w-4" />Enforce MFA</label><div className="grid gap-3 md:grid-cols-2"><div className="rounded-lg border border-gray-200 p-4"><p className="font-semibold"><Database className="mr-2 inline h-4 w-4" />/uploads/videos</p><p className="mt-2 text-xl font-bold">{formatBytes(storage?.videos.bytes ?? 0)}</p><p className="text-sm text-gray-500">{storage?.videos.files ?? 0} files</p></div><div className="rounded-lg border border-gray-200 p-4"><p className="font-semibold"><Database className="mr-2 inline h-4 w-4" />/uploads/attachments</p><p className="mt-2 text-xl font-bold">{formatBytes(storage?.attachments.bytes ?? 0)}</p><p className="text-sm text-gray-500">{storage?.attachments.files ?? 0} files</p></div></div><div className="flex flex-wrap gap-3"><button type="button" disabled={busy} onClick={() => void cleanup()} className="btn-secondary"><Trash2 className="h-4 w-4" />Run Storage Cleanup</button><input value={recipient} onChange={(event) => setRecipient(event.target.value)} placeholder="Test email recipient" className="input-field max-w-xs" /><button type="button" disabled={busy} onClick={() => void testEmail()} className="btn-secondary"><Mail className="h-4 w-4" />Send Test Email</button><button type="button" disabled={busy} onClick={() => void save()} className="btn-primary"><Save className="h-4 w-4" />Save new settings</button></div></section>;
}
