import { useEffect, useState } from 'react';
import { Activity, CheckCircle2, RefreshCw, Save, WifiOff } from 'lucide-react';
import { fetchAdminAiModels, fetchAiHealth, fetchAiUsage, saveAdminAiModel, testAiConnection, type AdminAiModel, type AiHealth, type AiProvider, type AiUsage } from '@/lib/adminAiRepository';

const providers: AiProvider[] = ['OpenAI', 'Gemini', 'Ollama', 'HuggingFace', 'Custom'];
type Draft = AdminAiModel & { api_key: string; tested: boolean };
export function AdminAiEnhancements() {
  const [models, setModels] = useState<Draft[]>([]); const [health, setHealth] = useState<AiHealth | null>(null); const [usage, setUsage] = useState<AiUsage | null>(null); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const load = async () => { try { const [nextModels, nextHealth, nextUsage] = await Promise.all([fetchAdminAiModels(), fetchAiHealth(), fetchAiUsage()]); setModels(nextModels.map((model) => ({ ...model, api_key: '', tested: false }))); setHealth(nextHealth); setUsage(nextUsage); } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : 'Unable to load AI telemetry.'); } };
  useEffect(() => { void load(); }, []);
  const update = <K extends keyof Draft>(id: string, key: K, value: Draft[K]) => setModels((current) => current.map((model) => model.id === id ? { ...model, [key]: value, tested: key === 'api_key' || key === 'api_endpoint' ? false : model.tested } : model));
  const test = async (model: Draft) => { try { await testAiConnection(model.provider, model.api_key, model.api_endpoint); update(model.id, 'tested', true); setNotice('Provider connection verified.'); } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : 'Connection test failed.'); } };
  const save = async (model: Draft) => { if (!model.tested) { setError('Test the provider connection first.'); return; } try { const saved = await saveAdminAiModel(model, model.api_key); setModels((current) => current.map((entry) => entry.id === model.id ? { ...saved, api_key: '', tested: true } : { ...entry, is_active: saved.is_active ? false : entry.is_active })); setNotice('Provider settings saved.'); } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : 'AI settings could not be saved.'); } };
  return <section className="card space-y-5 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[0.12em] text-primary-600">Live infrastructure</p><h2 className="text-lg font-semibold">Health, providers, and usage</h2></div><button type="button" onClick={() => void load()} className="btn-secondary"><RefreshCw className="h-4 w-4" />Refresh</button></div>{error && <p className="text-sm text-red-600">{error}</p>}{notice && <p className="text-sm text-emerald-600">{notice}</p>}<div className="grid gap-3 md:grid-cols-4"><div><p className="text-xs text-gray-500">Service status</p><p className="text-xl font-bold">{health?.status ?? 'Unknown'}</p><p className="text-sm text-gray-500">{health?.latency_ms ?? 0} ms · {health?.uptime_percent ?? 0}% uptime</p></div><div><p className="text-xs text-gray-500">Total tokens</p><p className="text-xl font-bold">{(usage?.total_tokens ?? 0).toLocaleString()}</p></div><div><p className="text-xs text-gray-500">Daily prompts</p><p className="text-xl font-bold">{usage?.daily_prompts ?? 0}</p></div><div><p className="text-xs text-gray-500">Estimated cost</p><p className="text-xl font-bold">${(usage?.estimated_cost ?? 0).toFixed(4)}</p></div></div><div className="space-y-4">{models.map((model) => <div key={model.id} className="rounded-lg border border-gray-200 p-4 dark:border-gray-700"><div className="grid gap-3 md:grid-cols-4"><select value={model.provider} onChange={(event) => update(model.id, 'provider', event.target.value as AiProvider)} className="input-field">{providers.map((provider) => <option key={provider}>{provider}</option>)}</select><input value={model.model_id} onChange={(event) => update(model.id, 'model_id', event.target.value)} className="input-field" placeholder="Model ID" /><input type="password" value={model.api_key} onChange={(event) => update(model.id, 'api_key', event.target.value)} className="input-field" placeholder={model.api_key_masked ?? 'API key'} autoComplete="new-password" /><div className="flex gap-2"><button type="button" onClick={() => void test(model)} className="btn-secondary" title="Test connection">{model.tested ? <CheckCircle2 className="h-4 w-4 text-emerald-600" /> : <WifiOff className="h-4 w-4" />}</button><button type="button" onClick={() => void save(model)} className="btn-primary" title="Save provider"><Save className="h-4 w-4" /></button></div></div></div>)}</div></section>;
}
